# __________ __                           __________                __   __        __                            ________
# \______   \  | _____  ___ __  __________\______   \_____ ________/  |_|__| ____ |  |   ____   ______    ___  _|   ____/
#  |     ___/  | \__  \<   |  |/ __ \_  __ \     ___/\__  \\_  __ \   __\  |/ ___\|  | _/ __ \ /  ___/    \  \/ /____  \ 
#  |    |   |  |__/ __ \\___  \  ___/|  | \/    |     / __ \|  | \/|  | |  \  \___|  |_\  ___/ \___ \      \   //       \
#  |____|   |____(____  / ____|\___  >__|  |____|    (____  /__|   |__| |__|\___  >____/\___  >____  >      \_//______  /
#                     \/\/         \/                     \/                    \/          \/     \/                 \/ 

# ==================================================== #
#                PlayerParticles Config                #
#               Welcome to the beginning               #
# ==================================================== #

# This value is the version of the plugin that last modified the config file
# Changing this value will reset your config on the next server reload / restart. 
# I don't recommend changing it
version: 5.3

# Check for new versions of the plugin
# Default: true
check-updates: true

# The .lang file to use in the ./lang/ folder
# Default: 'default.lang'
lang-file: 'default.lang'

# If you're using other plugins to execute commands you may wish to turn off messages
# Default: true
messages-enabled: true

# Whether or not to use the message-prefix field when displaying messages
# Default: true
use-message-prefix: true

# The prefix to use for all PlayerParticle messages
# This is useless if use-message-prefix is set to false
# Default: '&7[&3PlayerParticles&7]'
message-prefix: '&7[&3PlayerParticles&7]'

# If the command /pp gui is enabled
# Disable this if you have your own custom GUI through another plugin
# Default: true
gui-enabled: true

# The worlds which this plugin is disabled in
# Remove the [] before you enter world names
# Default: []
disabled-worlds: []
#  - your_world_name_here
#  - add_more_under_these

# The maximum number of particles a player can apply at once
# Default: 3
max-particles: 3

# The maximum number of groups a player can have saved
# Default: 10
max-groups: 10

# Max fixed effects per player
# Default: 5
max-fixed-effects: 5

# Max fixed effect creation distance
# Determines how far away a player may create a fixed effect from themselves
# This measurement is in blocks
# Set to 0 for infinite distance
# Default: 32
max-fixed-effect-creation-distance: 32

# How many ticks to wait before spawning more particles
# Increasing this value may cause less lag (if there was any), but will decrease prettiness
# Only use whole numbers greater than or equal to 1
# Going over 3 will likely look terrible
# Default: 1
ticks-per-particle: 1

# ================================================================ #
#                     DATABASE CONFIGURATION                       #
# Information:                                                     #
# * This is meant for people who have multiple servers connected   #
#   together through BungeeCord. Unless you have multiple servers, #
#   it is recommended to keep the database storage disabled for    #
#   the best performance!                                          #
# ================================================================ #

# Enable Database
# Default: false
database-enable: false

# ------------------------------------------------------------------- #
# The following are only required if database-enable is set to 'true' #
# ------------------------------------------------------------------- #

# Database Hostname
# Default: ''
database-hostname: ''

# Database Port
# Default: 3306
database-port: 3306

# Database Name
# Default: ''
database-name: ''

# Database User Name
# Default: ''
database-user-name: ''

# Database User Password
# Default: ''
database-user-password: ''

# =================================================================== #
#                        GUI ICON SETTINGS                            #
# This configuration option allows you to change any of the GUI       #
# icons to whatever block/item you want.                              #
#                                                                     #
# Important Notes:                                                    #
# * If any of the block/item names are invalid the icon in the GUI    #
#   will be the barrier icon to show that it failed to load.          #
# * Do NOT change the particle/style name                             #
# * You MUST use the Spigot-given name for it to work. You can see    #
#   all the Spigot-given names at the link below:                     #
#   https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html #
# =================================================================== #

gui-icon: 
  main-menu:
    EFFECT: BLAZE_POWDER
    STYLE: NETHER_STAR
    DATA: BOOK
  effect: # 1.13 and up
    AMBIENT_ENTITY_EFFECT: BEACON
    ANGRY_VILLAGER: IRON_DOOR
    BARRIER: BARRIER
    BLOCK: STONE
    BUBBLE: BUBBLE_CORAL
    BUBBLE_COLUMN_UP: MAGMA_BLOCK
    BUBBLE_POP: BUBBLE_CORAL_FAN
    CLOUD: WHITE_WOOL
    CRIT: IRON_SWORD
    CURRENT_DOWN: SOUL_SAND
    DAMAGE_INDICATOR: BOW
    DOLPHIN: DOLPHIN_SPAWN_EGG
    DRAGON_BREATH: DRAGON_BREATH
    DRIPPING_LAVA: LAVA_BUCKET
    DRIPPING_WATER: WATER_BUCKET
    DUST: REDSTONE
    ENCHANT: ENCHANTING_TABLE
    ENCHANTED_HIT: DIAMOND_SWORD
    END_ROD: END_ROD
    ENTITY_EFFECT: GLOWSTONE_DUST
    EXPLOSION: FIRE_CHARGE
    EXPLOSION_EMITTER: TNT
    FALLING_DUST: SAND
    FIREWORK: FIREWORK_ROCKET
    FISHING: FISHING_ROD
    FLAME: BLAZE_POWDER
    HAPPY_VILLAGER: DARK_OAK_DOOR
    HEART: POPPY
    INSTANT_EFFECT: SPLASH_POTION
    ITEM: ITEM_FRAME
    ITEM_SLIME: SLIME_BALL
    ITEM_SNOWBALL: SNOWBALL
    LARGE_SMOKE: COBWEB
    LAVA: MAGMA_CREAM
    MYCELIUM: MYCELIUM
    NAUTILUS: HEART_OF_THE_SEA
    NOTE: NOTE_BLOCK
    POOF: FIREWORK_STAR
    PORTAL: OBSIDIAN
    RAIN: PUFFERFISH_BUCKET
    SMOKE: TORCH
    SPELL: POTION
    SPIT: LLAMA_SPAWN_EGG
    SPLASH: SALMON
    SQUID_INK: INK_SAC
    SWEEP_ATTACK: GOLDEN_SWORD
    TOTEM_OF_UNDYING: TOTEM
    UNDERWATER: TURTLE_HELMET
    WITCH: CAULDRON
  effect-legacy: # 1.9 to 1.12
    AMBIENT_ENTITY_EFFECT: BEACON
    ANGRY_VILLAGER: IRON_DOOR
    BARRIER: BARRIER
    BLOCK: STONE
    BUBBLE: GLASS
    CLOUD: WOOL
    CRIT: IRON_SWORD
    DAMAGE_INDICATOR: BOW
    DRAGON_BREATH: DRAGONS_BREATH
    DRIPPING_LAVA: LAVA_BUCKET
    DRIPPING_WATER: WATER_BUCKET
    DUST: REDSTONE
    ENCHANT: ENCHANTMENT_TABLE
    ENCHANTED_HIT: DIAMOND_SWORD
    END_ROD: END_ROD
    ENTITY_EFFECT: GLOWSTONE_DUST
    EXPLOSION: FIREBALL
    EXPLOSION_EMITTER: TNT
    FALLING_DUST: SAND
    FIREWORK: FIREWORK
    FISHING: FISHING_ROD
    FLAME: BLAZE_POWDER
    FOOTSTEP: GRASS
    HAPPY_VILLAGER: WOOD_DOOR
    HEART: RED_ROSE
    INSTANT_EFFECT: POTION
    ITEM: ITEM_FRAME
    ITEM_SLIME: SLIME_BALL
    ITEM_SNOWBALL: SNOWBALL
    LARGE_SMOKE: WEB
    LAVA: MAGMA_CREAM
    MYCELIUM: MYCEL
    NOTE: NOTE_BLOCK
    POOF: FIREWORK_CHARGE
    PORTAL: OBSIDIAN
    RAIN: LAPIS_BLOCK
    SMOKE: TORCH
    SPELL: GLASS_BOTTLE
    SPIT: PUMPKIN_SEEDS
    SPLASH: FISH
    SWEEP_ATTACK: GOLD_SWORD
    TOTEM_OF_UNDYING: TOTEM
    UNDERWATER: BOAT
    WITCH: CAULDRON
  style: # 1.13 and up
    ARROWS: BOW
    BATMAN: COAL
    BEAM: POWERED_RAIL
    BLOCKBREAK: IRON_PICKAXE
    BLOCKEDIT: DISPENSER
    BLOCKPLACE: OAK_PLANKS
    CHAINS: TRIPWIRE_HOOK
    COMPANION: NAME_TAG
    CUBE: STONE
    FEET: GRASS
    HALO: END_PORTAL_FRAME
    HURT: CACTUS
    INVOCATION: ENDER_EYE
    MOVE: PISTON
    NONE: GLASS_PANE
    ORBIT: ENCHANTING_TABLE
    OVERHEAD: GLOWSTONE
    POINT: STONE_BUTTON
    QUADHELIX: NAUTILUS_SHELL
    NORMAL: DIRT
    RINGS: STRING
    SPHERE: HEART_OF_THE_SEA
    SPIN: BEACON
    SPIRAL: HOPPER
    SWORDS: IRON_SWORD
    THICK: COBWEB
    VORTEX: GLOWSTONE_DUST
    WINGS: ELYTRA
  style-legacy:  # 1.9 to 1.12
    ARROWS: BOW
    BATMAN: COAL
    BEAM: POWERED_RAIL
    BLOCKBREAK: IRON_PICKAXE
    BLOCKEDIT: DISPENSER
    BLOCKPLACE: WOOD
    CHAINS: TRIPWIRE_HOOK
    COMPANION: NAME_TAG
    CUBE: STONE
    FEET: GRASS
    HALO: ENDER_PORTAL_FRAME
    HURT: CACTUS
    INVOCATION: EYE_OF_ENDER
    MOVE: PISTON_BASE
    NORMAL: DIRT
    ORBIT: ENCHANTMENT_TABLE
    OVERHEAD: GLOWSTONE
    POINT: STONE_BUTTON
    QUADHELIX: ACTIVATOR_RAIL
    RINGS: STRING
    SPHERE: SNOW_BALL
    SPIN: BEACON
    SPIRAL: HOPPER
    SWORDS: IRON_SWORD
    THICK: VINE
    VORTEX: GLOWSTONE_DUST
    WINGS: ELYTRA

# That's everything! You reached the end of the configuration.
# Enjoy the plugin!
